In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.decomposition import PCA
from sklearn.svm import SVR
from sklearn.metrics import r2_score, mean_squared_error
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv('data/07_flats_EDA.csv')
df.dropna(inplace=True)

In [3]:
df['price_cr'] = df['price_cr']*1.7    #since, the dataset is 4 years old, increasing prices by 70%

In [4]:
df.head(2)

,area_sqm,bedroom,bathroom,balcony,addl_room,sector,landmark_count,has_hospital_or_clinic,has_police_stn,has_fire_stn,has_mall,has_market,has_park,has_bank_or_atm,has_institute,has_airport,has_rly_stn,has_metro_stn,has_expy,has_petrol_pump,has_hotel,has_temple_or_church,has_famous_chowk,has_club,has_stadium,has_restro_cafe,area_type,floor_rise,age,society,city,price_cr
0,83.61,2.0,2.0,1.0,0.0,sector 7,50.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,carpet,mid,new,maa bhagwati residency,gurgaon,1.3005
1,60.39,2.0,2.0,1.0,0.0,sector 3,48.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,carpet,low,old,apna enclave,gurgaon,1.4450


In [5]:
le = LabelEncoder()
for col in df.columns:
    if df[col].dtype == 'object':
        df[col] = le.fit_transform(df[col])

In [6]:
X = df.iloc[:,1:]
y = df['price_cr']

In [7]:
#train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
#Scaling X
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [9]:
X_train_scaled.shape[1]

31

In [10]:
X_train_scaled = pd.DataFrame(X_train_scaled)

In [11]:
#using PCA to reduce dimensionality
pca = PCA(n_components=0.95)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

In [12]:
X_train_pca.shape[1]

26

In [13]:
pca.components_

array([[ 9.07822865e-02,  1.30748853e-01,  1.50463147e-01,
         1.33106650e-01,  2.58252437e-02, -2.98749748e-01,
         1.34969338e-02, -4.63363766e-02, -1.69241351e-02,
         2.96018064e-01, -1.49700794e-01,  1.41276081e-01,
        -3.16383338e-01,  2.63714885e-01,  3.18023746e-01,
         4.35158053e-02,  2.84915499e-02,  2.23232728e-01,
        -2.43529534e-01,  2.26599429e-01, -2.98317056e-01,
        -1.12403803e-01, -1.19547151e-02,  1.14837431e-01,
        -2.82327904e-01,  1.65964383e-01, -9.80217449e-02,
        -1.87345778e-01, -1.91676417e-03, -5.23260212e-02,
         9.02315388e-02],
       [ 4.19788838e-01,  4.33388036e-01,  2.87559324e-01,
         2.75080694e-01, -6.32039922e-02,  2.14248742e-01,
         1.60768844e-01,  5.80818524e-02,  1.82867075e-02,
        -1.25634882e-02,  1.57165147e-01,  1.69183133e-01,
         1.73224702e-01,  2.28641330e-04,  9.68951576e-03,
        -3.64875126e-02,  1.46405446e-01, -1.03625027e-01,
         4.93025325e-02,  6.23

In [14]:
pca.explained_variance_

array([5.03670091, 3.18792607, 2.01097724, 1.73579498, 1.40030085,
       1.37400313, 1.21221471, 1.1017453 , 1.03006511, 1.01331613,
       0.98954204, 0.9071451 , 0.89007557, 0.78953632, 0.77139363,
       0.72773651, 0.69485352, 0.66471865, 0.62136946, 0.60363811,
       0.56355481, 0.54730291, 0.49626062, 0.45436567, 0.44325493,
       0.42146521])

In [15]:
pca.explained_variance_ratio_

array([0.16240428, 0.10279206, 0.06484231, 0.05596928, 0.04515155,
       0.0443036 , 0.03908687, 0.03552487, 0.0332136 , 0.03267355,
       0.03190697, 0.02925015, 0.02869976, 0.02545795, 0.02487295,
       0.02346527, 0.02240498, 0.02143331, 0.02003555, 0.01946381,
       0.01817136, 0.01764733, 0.01600152, 0.01465065, 0.01429239,
       0.0135898 ])

In [16]:
pca.explained_variance_ratio_.sum()

0.9573057065612774

In [17]:
y_train.unique()

array([ 1.3005,  9.6815,  3.179 ,  2.601 ,  4.8552,  5.3465,  7.0805,
        1.3583,  4.2483,  3.8726,  1.5317,  3.9304,  5.202 , 10.115 ,
        4.335 ,  3.8148,  3.3524,  8.6411,  3.1212,  0.7225,  4.046 ,
        2.8611,  1.2138, 23.8425,  1.445 ,  4.4795,  8.381 ,  3.6125,
       18.785 ,  1.734 , 14.45  ,  3.0345,  5.5199,  1.5606,  7.5718,
        0.867 ,  2.312 ,  0.6358,  1.0982,  4.624 ,  4.1905,  2.5143,
        2.89  ,  3.2368,  3.468 ,  4.913 ,  8.092 , 11.849 ,  3.9015,
        4.1038, 13.7275,  1.156 ,  5.0575,  5.0864,  2.1675,  1.3872,
        3.4102,  5.491 ,  8.5255,  3.3235, 10.693 ,  4.9997,  2.8322,
       11.56  ,  5.2887, 14.2766,  2.5432,  9.5081,  3.757 ,  5.4043,
       10.5485,  2.7455,  0.8092,  5.2598, 22.542 ,  6.647 ,  0.7514,
        4.0171,  3.7859,  4.7974,  5.9245,  2.4565,  6.2713, 11.0687,
        2.5721,  3.6414,  4.3061,  5.8667,  1.1271,  2.023 ,  6.7915,
       26.01  , 10.404 ,  1.3294,  4.7685,  5.1442,  7.6585,  0.7803,
        2.2542,  2.4

In [18]:
#model 1: RF Regression
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train_pca, y_train)
y_pred = model.predict(X_test_pca)

print(f"RMSE     : {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R2_score : {r2_score(y_test, y_pred)}")

RMSE     : 1.2381255889004914
R2_score : 0.8928979013522477


In [19]:
#model 2: XG Boost Regression
from xgboost import XGBRegressor
model = XGBRegressor(objective='reg:squarederror',n_estimators=100, 
                         learning_rate=0.1,max_depth=5,random_state=42)
model.fit(X_train_pca, y_train)
y_pred = model.predict(X_test_pca)

print(f"RMSE     : {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R2_score : {r2_score(y_test, y_pred)}")

RMSE     : 1.2708340480174862
R2_score : 0.8871643680189576


In [20]:
#model 3: SVR Regression
from sklearn.svm import SVR
model = SVR(kernel='rbf', C=100, gamma=0.1, epsilon=.1)
model.fit(X_train_pca, y_train)
y_pred = model.predict(X_test_pca)

print(f"RMSE     : {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R2_score : {r2_score(y_test, y_pred)}")

RMSE     : 1.1953478770269186
R2_score : 0.9001708872935754


In [21]:
#model 4: SVR Regression
from sklearn.svm import SVR
model = SVR(kernel='rbf', C=70, gamma=0.06, epsilon=.14)
model.fit(X_train_pca, y_train)
y_pred = model.predict(X_test_pca)

print(f"RMSE     : {np.sqrt(mean_squared_error(y_test, y_pred))}")
print(f"R2_score : {r2_score(y_test, y_pred)}")

RMSE     : 0.7477416260866329
R2_score : 0.9609364509208721


#### the best model is Support Vector Regressor (SVR) with 86% R2 Score